name: CiaraHub
version: 1.0
main: com.ciarahub.CiaraHub
api-version: 1.19
description: Plugin pour gérer diverses fonctionnalités de hub sur un serveur Minecraft.

commands:
  spawn:
    description: Retourne le joueur au point de spawn.
    usage: /spawn

  t:
    description: Commande pour gérer le temps.
    usage: /t <day|night>

  testgui:
    description: Ouvre le GUI de test.
    usage: /<command>

  getrank:
    description: Affiche le rang du joueur
    usage: /<command>


permissions:
  ciarahub.spawn:
    description: Permet au joueur d'utiliser la commande /spawn.
    default: op
  ciarahub.time:
    description: Permet au joueur de changer le temps avec /t.
    default: op
  ciarahub.getrank:
    description: Permet au joueur de voir son rang avec /getrank.
    default: op
